add section message
hapo-lam-nv/hapo-lam-elearning pull request #9
Opened 2020-07-20 10:23 UTC by hapo-lam-nv

add section message

2020-07-20 10:29 UTC, gs-chinhnc requested changes

2020-07-20 10:29 UTC, hapo-chinhnc commented on css/style.css
> +  padding: 10px 0px 0px 60px;
0px nè

2020-07-20 10:29 UTC, hapo-chinhnc commented on css/style.css
> +  letter-spacing: -0.02em;
short nè

2020-07-20 10:29 UTC, hapo-chinhnc commented on css/style.css
> +  right: 0%;
0% ->0

2020-07-20 10:29 UTC, hapo-chinhnc commented on css/style.css
> +  /*  */
k có comment thì xoá đi

2020-07-20 10:38 UTC, gs-chinhnc approved these changes
LGTM

2020-07-20 10:40 UTC, Hapo-congbv approved these changes
LGTM

2020-07-21 01:05 UTC, hapo-datnd commented on css/style.css
> +  box-shadow: 0px 0px 8px rgba(0, 0, 0, 0.25);
`0px -> 0`

2020-07-21 01:30 UTC, hapo-nghialuu commented on css/style.css
> +  /* or 142% */
bỏ comment đoạn này và trên đi em

2020-07-21 01:30 UTC, hapo-nghialuu commented on css/style.css
> +  position: sticky;
sao lại dùng position sticky đoạn này nhỉ?

2020-07-21 01:31 UTC, hapo-nghialuu commented on css/style.css
> +  margin-left: 970px;
sao laok margin-left lớn như thế này?

2020-07-21 01:32 UTC, hapo-lam-nv commented on css/style.css
> +  position: sticky;
em css cho cái icon message

2020-07-21 01:33 UTC, hapo-lam-nv commented on css/style.css
> +  position: sticky;
em cho nó bám dính vào giao diện anh

2020-07-21 01:34 UTC, hapo-lam-nv commented on css/style.css
> +  margin-left: 970px;
em cho icon message về góc phải màn hình

2020-07-21 02:35 UTC, hapo-nghialuu commented on css/style.css
> +  top: 350px;
sao cái này không để là bottom: 0px hoặc tầm 50px nhỉ? thế có phải dễ hơn không?

2020-07-21 03:00 UTC, hapo-lam-nv commented on css/style.css
> +  top: 350px;
do em không set chiều cao của hapo-fixed nên nếu để bottom 0px thì không nhìn thấy hình ảnh message
Như anh nói là nếu để bottom 0px thì phải set height cho hapo-fixed

2020-07-21 04:04 UTC, hapo-nghialuu approved these changes
LGTM

2020-07-21 04:05 UTC, merged